spring:
  application:
    name: dashboard API
server:
  port: 4050


  spring:
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    h2:
      console:
        enabled: true

jwt:
  secret: SuperInnov8vex784335@#1&
  expiration: 3600000 # milliseconds (1 hour)
